### PR TITLE
made things less shit again

### PR DESCRIPTION
**Pull request by Reaxt00**
Things in the meta where too complicated so I changed it pls merge <3

### CODE REVIEW

**Comment by MeguminSama** [comment]
@Reaxt00 in my next push I'll be making the metadata more suitable for readability + some other changes, you can close this if you like :^)

**Comment by apap04** [comment]
close reeeeeeeeeeeeeeeee

**Comment by MeguminSama** [comment]
lmao

**Comment by MeguminSama** [comment]
oh. okay

**Pull request closed without merging**
