### PR TITLE
fixed minor stuff.

### PR DESCRIPTION
**Pull request by apap04**

### CODE REVIEW

**Comment by MeguminSama** [comment]
i hate inconsistency in html like that.
<meta> tags dont need cancelling, <link> tags can just have <link blah /> and <script> tags MUST have a seperate closing tag grr

**Comment by apap04** [comment]
@MeguminSama ahem bin

**Comment by MeguminSama** [comment]
@apap04 ahem meme

**Comment by apap04** [comment]
@MeguminSama lemme lick hand nya

**Comment by apap04** [comment]
@MeguminSama <@143093011402719232> Can you merge this?

**Comment by MeguminSama** [comment]
i dont have write access on here. only the docs.

**Comment by apap04** [comment]
darn. @binsenpai merge this pls kthx

**Pull request merged**
