### PR TITLE
Made some minor tweaks 

### PR DESCRIPTION
**Pull request by Reaxt00**
Got rid of some useless stuff, gave credits where due, and credited things I used to make it,

### CODE REVIEW

**Comment by Reaxt00** [comment]
pls merge

**Comment by apap04** [comment]
hot

**Comment by MeguminSama** [comment]
nice, but pls stop adding the "code added by x" comments lmao
It's a company :mmLol:

**Comment by Reaxt00** [comment]
but no one's gonna look in the source code

**Comment by MeguminSama** [comment]
except the people who do :^)

**Comment by Reaxt00** [comment]
gonna make more changes first

**Pull request merged**
