### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by MeguminSama**
## ignore commit 55e0416 & 2a8ded9
+ Stopped scrollbar from appearing even when page height is <= 100% (`overflow-y: hidden;`)
+ Simplified title
+ Simplified metadata
+ Referenced `css/home.css`

### CODE REVIEW

**Comment by apap04** [comment]
WOULD MERGE RN IF I HAD WRITE ACCESS AMIRITE HAHAHAHAHAHAHAHAHAHAHHAHAHAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH


😢 🔫 :feelsgood:

**Comment by titanswift** [comment]
what

**Comment by MeguminSama** [comment]
@titanswift fite me boi

**Comment by apap04** [comment]
@titanswift how'd you find this 👀

**Comment by MeguminSama** [comment]
@apap04 its public on shitpost central lmao

**Comment by apap04** [comment]
@MeguminSama oh shit

**Comment by MeguminSama** [comment]
LMAO

**Comment by apap04** [comment]
@MeguminSama send link\

**Comment by MeguminSama** [comment]
image
lol

**Comment by apap04** [comment]
why

**Comment by MeguminSama** [comment]
idk ask bin lol

**Comment by apap04** [comment]
what server

**Comment by MeguminSama** [comment]
https://discord.gg/tVP9q3

**Comment by titanswift** [comment]
cool

**Pull request merged**
