### PR TITLE
Fixed scrollbar appearance when using Bulma Theme (CDN)

### PR DESCRIPTION
**Pull request by MeguminSama**
Referenced `css/home.css` in `index.html` and added html key to CSS, hiding the overflow-y
+ modified Metadata
+ set charset to UTF-8 for compatability.

### CODE REVIEW

**Comment by apap04** [comment]
thx for referring

**Comment by MeguminSama** [comment]
:^)

**Comment by apap04** [comment]
change filename
home.css -> main.css

**Comment by apap04** [comment]
pls

**Comment by MeguminSama** [comment]
i did :^)

**Comment by apap04** [comment]
o shitt

**Comment by MeguminSama** [comment]
fuck this shit

**Comment by apap04** [comment]
whAT nO

**Comment by MeguminSama** [comment]
:^)
i realised that since that isnt gonna be the homepage theme, having it main.css is a bad idea

**Pull request closed without merging**
