### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by YazawaNic0**
idek

### CODE REVIEW

**Comment by PryDt** [comment]
isnt jquery just bloat?

you can use `document.getElementById` type functions without that massive library...

**Comment by YazawaNic0** [comment]
oh i have no idea what im doing <3

**Comment by YazawaNic0** [comment]
i just want to make it look snazzy

**Comment by apap04** [comment]
revert please

**Comment by apap04** [comment]
@Reaxt00 can you revert this

**Pull request merged**
