### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by YazawaNic0**
Heres my second try. Hope it doesnt look as bad as last time

### CODE REVIEW

**Comment by binuwu** [comment]
focus in school my dude

**Comment by binuwu** [comment]
also lol conflicts u messed up

**Comment by YazawaNic0** [comment]
i fixed it dammit

**Comment by binuwu** [comment]
http://pixel.is-my.world/mgojfi.png

**Comment by YazawaNic0** [comment]
also im in health everythin cool here

**Comment by binuwu** [comment]
ok

**Comment by YazawaNic0** [comment]
there

**Comment by YazawaNic0** [comment]
i did a dang fixeroooooolli

**Pull request merged**
