### PR TITLE
Revert "Update index.html"

### PR DESCRIPTION
**Pull request by binuwu**
please stop hurting yourself @YazawaNic0

### CODE REVIEW

**Comment by YazawaNic0** [comment]
oh come on

**Comment by YazawaNic0** [comment]
god dammit whats wrong this time

**Comment by binuwu** [comment]
@Reaxt00 this is trash, literal trash LMFAO

**Comment by YazawaNic0** [comment]
oh COME ON IM A BEGINNER 😢

**Comment by binuwu** [comment]
ur code isn't bad, the design is

**Comment by YazawaNic0** [comment]
this was all i could whip up before school started 😢

**Comment by binuwu** [comment]
is discord blocked there

**Comment by binuwu** [comment]
art isn't a thing of being good or not, it's not experience or etc. just take the files, set it up on ur own domain/whatever and @Reaxt00 will have a look at it.

**Comment by binuwu** [comment]
>library
lol.

**Comment by YazawaNic0** [comment]
discord is blocked here

**Comment by binuwu** [comment]
alright i'll give you a proxy to use when you're home.

**Comment by YazawaNic0** [comment]
uh THIS IS A SCHOOL CHROMEBOOK IM FINNA DIE

**Comment by binuwu** [comment]
a proxy doesn't do shit it just routes all your HTTP requests through it

**Comment by binuwu** [comment]
meaning you can access blocked sites.

**Comment by YazawaNic0** [comment]
nu uh i aint doin anything to this chromebook. I don't want to die

**Comment by YazawaNic0** [comment]
Remember this is CASEY THEY WILL USE ANY REASON TO SHOOT US 😆

**Comment by binuwu** [comment]
ur not gonna die u just have to set the proxy in wifi settings?? it's common, ur school has its own proxy and google's proxy is a well known one

**Comment by PryDt** [comment]
I just use a VPN at school

**Comment by YazawaNic0** [comment]
-Plus all the proxy websites are blocked ;-;-
They also have the proxy settings locked on their proxy. I checked the settings

**Comment by binuwu** [comment]
he can't use vpn cos chromebook, everything is blocked, proxy is his only option. wouldn't be surprised if proxies r blocked too. 

if they are then just lmao buy a new network card ez win

**Comment by binuwu** [comment]
AAAAA DAMN IT

**Comment by YazawaNic0** [comment]
ez win

**Comment by binuwu** [comment]
RIP U LMFAO

**Comment by binuwu** [comment]
wait what if i got you a wifi hotspot thing like
you carry it in your pocket, it connects to WSCD (the wifi name yes i still remember it), and then proxies the internet?

**Comment by binuwu** [comment]
name it the `idol only internet`

**Comment by binuwu** [comment]
you know















>greentext pls


























mmm

**Comment by binuwu** [comment]
i did that before but like it's watch_dogs hacker level shit.

also back when i went to casey middle they barely had any blocked and our grade didn't have chromebooks

if you remember they only gave chromebooks to anyone coming into grade 5 the year after i went to 6th grade xd rip lmao

**Comment by YazawaNic0** [comment]
ill just stick with WCSD

**Comment by binuwu** [comment]
lol

**Comment by binuwu** [comment]
back when we used windows computers in the computer lab, that was the day.

**Comment by YazawaNic0** [comment]
well we still do. Except the library now has mini chromeboxes

**Comment by YazawaNic0** [comment]
and most of the computers have windows 10

**Comment by binuwu** [comment]
I can you know uh make a website that talks to specific channels in Discord for you (no token password needed and only in html and js

You'll need to host it on google sites so it doesn't get blocked LOL

**Comment by YazawaNic0** [comment]
Sure ill do that 😆

**Comment by YazawaNic0** [comment]
What if i host it on my domain. BeCUZ I GOT THEM TO WHITELIST MY DOMAIN AAAAAA

**Comment by binuwu** [comment]
lol wut rly?

**Comment by binuwu** [comment]
I wonder if they have IRC blocked.

**Comment by binuwu** [comment]
It doesn't operate on HTTP so.

**Comment by binuwu** [comment]
Actually, that gives me 2 good ideas:

Shoot me a DM on Discord when you get home I'll start preparing them, it might be useful to anyone who wants to access Discord with a blocked internet connection lol.

**Comment by YazawaNic0** [comment]
pffttt they probably dont have IRC unblocked

**Comment by YazawaNic0** [comment]
alright

**Comment by YazawaNic0** [comment]
Well im bored so dont leave me. Im in earth science lol

**Comment by binuwu** [comment]
Like `http://relay.com/relay_url?website=http://wikipedia.com`. Our backend code could look like this:
```cs
[Route("/relay_url")]
public async Task<IActionResult> relay_url_endpoint()
{
	string request_url = Request.Query["website"];
	if(String.IsNullOrWhiteSpace(request_url)
		return BadRequest(new { error = true, message = "No URI provided" });
	HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, request_url);
	HttpResponseMessage response = await Client.SendAsync(request);

	//do some check to make sure response status code is ok and if not notify the user
	//maybe even replace the content of the body where it requests assets and replaces with URL forwarder?

	Response.StatusCode = 200;
	Response.ContentType = response.Content.Headers.ContentType;
	return Ok(await response.Content.ReadAsStringAsync());
}
```

Simple easy code.

**Comment by YazawaNic0** [comment]
Okay lets focus on otako for now 😓

**Comment by YazawaNic0** [comment]
also like what if they block sockets

**Comment by PryDt** [comment]
https://www.quora.com/What-are-some-alternatives-to-Websocket

I still think websockets are the way to go

**Comment by MeguminSama** [comment]
HTTP Streaming seems suspiciously similar to long polling :^)

**Comment by YazawaNic0** [comment]
QUORA IS MY LIFEEEEE

**Comment by PryDt** [comment]
I just realized this wasn't for otako -_-

**Comment by YazawaNic0** [comment]
hehe

**Comment by YazawaNic0** [comment]
Bins the one who directed this so far off topic 😆

**Comment by MeguminSama** [comment]
xd

**Comment by MeguminSama** [comment]
noobs

**Comment by YazawaNic0** [comment]
megu dont be mean

**Comment by MeguminSama** [comment]
its joke

**Comment by YazawaNic0** [comment]
you little nugget

**Comment by MeguminSama** [comment]
oi

**Comment by MeguminSama** [comment]
rude boi

**Comment by YazawaNic0** [comment]
no u

**Comment by PryDt** [comment]
*spicy*

**Comment by YazawaNic0** [comment]
megu san

**Comment by YazawaNic0** [comment]
spicy m egu

**Comment by MeguminSama** [comment]
>spamming #genral chat

**Comment by MeguminSama** [comment]
no u

**Comment by YazawaNic0** [comment]
dammit megumin

**Comment by MeguminSama** [comment]
yeah vro i hit em' with that `no u`

**Comment by PryDt** [comment]
> It ends all

**Comment by MeguminSama** [comment]
>no u

**Comment by YazawaNic0** [comment]
> no u

**Comment by YazawaNic0** [comment]
# IM GETTING MORE AND MORE BORED BECAUSE IM IN SCHOOL SOMEONE SAVE ME

**Comment by MeguminSama** [comment]
###no u

**Comment by YazawaNic0** [comment]
dammit megu

**Comment by MeguminSama** [comment]
xd

**Comment by MeguminSama** [comment]
## no u

**Comment by YazawaNic0** [comment]
# **in before bin locks this conversation and says "off topic"**

**Comment by binuwu** [comment]
@PryDt @YazawaNic0 @MeguminSama I was talking about his middle school's network and **raw sockets** not WebSockets. (To bypass school block on websites)

**Comment by binuwu** [comment]
went way off topic

**Comment by MeguminSama** [comment]
I was pitching in on @PryDt's post :^)

**Pull request merged**
