### PR TITLE
hehe this is so that we have another place to talk

### PR DESCRIPTION
**Pull request by YazawaNic0**
hehe get fuked bin

### CODE REVIEW

**Comment by YazawaNic0** [comment]
Heres hoping he doesnt catch it

**Comment by YazawaNic0** [comment]
# **Also dont fucking merge it please**

**Comment by MeguminSama** [comment]
uhm no.

**Comment by YazawaNic0** [comment]
OH COME ON

**Comment by YazawaNic0** [comment]
wait we can still talk

**Comment by YazawaNic0** [comment]
im fine with this. Discord is blocked so im fuckin lonely here in study hall

**Comment by MeguminSama** [comment]
why dont u study

**Comment by YazawaNic0** [comment]
pffttt

**Comment by YazawaNic0** [comment]
great joke megumin

**Comment by YazawaNic0** [comment]
whomst the fuck actually studys here in school

**Comment by MeguminSama** [comment]
ok ffs use a proxy and stop spamming chat with embeds

**Comment by YazawaNic0** [comment]
no u

**Comment by MeguminSama** [comment]
stfu

**Comment by YazawaNic0** [comment]
oemaya megu san no need to be so grumpy

**Comment by YazawaNic0** [comment]
okay ill stop 😆

**Pull request closed without merging**
