### PR TITLE
Updating the website completely.

### PR DESCRIPTION
**Pull request by apap04**
This PR is for keeping track of things that need to be completed. 

- [ ] Add info on how the app works and what it is in index.html.
- [ ] Fix CSS. (Editing the Bulma theme. Or let's just create our own theme.)
- [ ] Add contact page 
- [ ] Make use of custom css files.
- [ ] Add jobs page
- [ ] Create custom theme (not required. just a suggestion.)
- [ ] Add links to other pages (docs, status page etc.)

### CODE REVIEW

**Comment by binsenpai** [comment]
Should I close this or merge it?

**Comment by binsenpai** [comment]
We'll be working on our own CSS theme, probbaly going to use Bootstrap 4 with it

**Comment by Reaxt00** [comment]
No this is a good one
heck off

**Comment by MeguminSama** [comment]
+1 for bootstrap

**Comment by georgebyrom** [comment]
thank god its not some shitty css sheet

**Comment by apap04** [comment]
@Reaxt00 the fucking margin-bottom in the subtitles class annoys me.
so nu :(

**Pull request merged**
