### PR TITLE
Revert "Update index.html"

### PR DESCRIPTION
**Pull request by Reaxt00**
THIS IS DISGUSTING

### CODE REVIEW

**Comment by apap04** [comment]
E E E W W WWEW EW EW
a
a
a
a
a
a

**Comment by Reaxt00** [comment]
@binuwu PLS

**Comment by binuwu** [comment]
"404 not found lol what "

**Comment by binuwu** [comment]
WHAT

**Comment by apap04** [comment]
where

**Comment by apap04** [comment]
i get it that nico is a beginner

**Comment by binuwu** [comment]
k

**Comment by binuwu** [comment]
boom

**Pull request merged**
